FROM maven:3.6.0-jdk-8

MAINTAINER Claude-Clement Yapo (yjeandavid@hotmail.com)

COPY . /tmp

RUN cd /tmp && mvn package && mkdir ../var/microcommerceapi && cd target \
	&& mv microcommerceapi-1.0.0-SNAPSHOT.jar ../../var/microcommerceapi/microcommerceapi.jar \
	&& mkdir ../../home/Documents && mkdir ../../home/Documents/projet \
	&& mkdir ../../home/Documents/projet/microcommerce && mkdir ../../home/Documents/projet/microcommerce/microcommercedb
	

#COPY /target/microcommerceapi-1.0.0-SNAPSHOT.jar ../var/microcommerceapi/microcommerceapi.jar

WORKDIR ../var/microcommerceapi

#executer une commande dans le container
#RUN bash -c 'ls /var/microcommerceapi'

EXPOSE 9090

ENTRYPOINT ["java", "-jar", "/var/microcommerceapi/microcommerceapi.jar"]